from enum import Enum


class JobStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    PARSED = "PARSED"
    SCORED = "SCORED"
    DRAFTED = "DRAFTED"
    VERIFIED = "VERIFIED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    PACKET_BUILT = "PACKET_BUILT"
    SUBMITTED = "SUBMITTED"
    FOLLOWUP_SCHEDULED = "FOLLOWUP_SCHEDULED"
    CLOSED = "CLOSED"


class SourceType(str, Enum):
    RSS = "RSS"
    MANUAL_JSON = "MANUAL_JSON"
    MANUAL_CSV = "MANUAL_CSV"


class ArtifactType(str, Enum):
    RESUME_DOCX = "RESUME_DOCX"
    RESUME_PDF = "RESUME_PDF"
    COVER_LETTER_DOCX = "COVER_LETTER_DOCX"
    COVER_LETTER_PDF = "COVER_LETTER_PDF"
    APPLICATION_PAYLOAD_JSON = "APPLICATION_PAYLOAD_JSON"
    VERIFICATION_REPORT_JSON = "VERIFICATION_REPORT_JSON"


class MessageStatus(str, Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    SENT = "SENT"
